// <auto-generated />
using System;
using DietPlannerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietPlannerAPI.Migrations
{
    [DbContext(typeof(DietPlannerDbContext))]
    [Migration("20260505172012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietPlannerAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietitianId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DietitianId = 1,
                            PatientName = "Jan Testowy"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Śniadanie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Obiad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kolacja"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DietPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.ToTable("DayPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "Poniedziałek",
                            DietPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayName = "Wtorek",
                            DietPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayName = "Środa",
                            DietPlanId = 2
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DietPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plan redukcyjny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plan zdrowego odżywiania"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Dietitian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dietitians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Anna Kowalska",
                            Specialization = "Dietetyka kliniczna"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Michał Nowak",
                            Specialization = "Dietetyka sportowa"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 370,
                            Name = "Płatki owsiane"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 89,
                            Name = "Banan"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 165,
                            Name = "Kurczak"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 15,
                            Name = "Sałata"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 98,
                            Name = "Twaróg"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Płatki owsiane z bananem i jogurtem",
                            Name = "Owsianka z owocami"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Lekki posiłek z warzywami i grillowanym kurczakiem",
                            Name = "Sałatka z kurczakiem"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Pełnoziarniste pieczywo z twarożkiem i warzywami",
                            Name = "Kanapki z twarożkiem"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("MealId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MealIngredients");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            MealId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            MealId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            MealId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            MealId = 3,
                            IngredientId = 5
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DietitianId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietitianId = 1,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DietitianId = 1,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DietitianId = 2,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Appointment", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Dietitian", "Dietitian")
                        .WithMany("Appointments")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DayPlan", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.DietPlan", "DietPlan")
                        .WithMany("DayPlans")
                        .HasForeignKey("DietPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlan");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Category", "Category")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.MealIngredient", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietPlannerAPI.Models.Meal", "Meal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.TimeSlot", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Dietitian", "Dietitian")
                        .WithMany("TimeSlots")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Category", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DietPlan", b =>
                {
                    b.Navigation("DayPlans");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Dietitian", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.Navigation("MealIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
