// <auto-generated />
using System;
using DietPlannerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietPlannerAPI.Migrations
{
    [DbContext(typeof(DietPlannerDbContext))]
    [Migration("20260507152856_CleanDayPlannerUi")]
    partial class CleanDayPlannerUi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietPlannerAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietitianId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DietitianId = 1,
                            PatientName = "Jan Testowy",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bmi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("BodyMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bmi = 26.0m,
                            MeasurementDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1,
                            WeightKg = 82.5m
                        },
                        new
                        {
                            Id = 2,
                            Bmi = 25.8m,
                            MeasurementDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1,
                            WeightKg = 81.8m
                        },
                        new
                        {
                            Id = 3,
                            Bmi = 25.4m,
                            MeasurementDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2,
                            WeightKg = 68.2m
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Śniadanie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Obiad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kolacja"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drugie śniadanie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Podwieczorek"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Przekąska"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DietPlanId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("MealId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("DayPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "Poniedziałek",
                            MealId = 1,
                            MealTime = "Śniadanie",
                            Notes = "Bez dodatkowego cukru",
                            PlanDate = new DateTime(2026, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayName = "Poniedziałek",
                            MealId = 2,
                            MealTime = "Obiad",
                            Notes = "Dodać więcej warzyw",
                            PlanDate = new DateTime(2026, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayName = "Wtorek",
                            MealId = 3,
                            MealTime = "Kolacja",
                            Notes = "Lekka kolacja po spacerze",
                            PlanDate = new DateTime(2026, 5, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DietPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plan redukcyjny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plan zdrowego odżywiania"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Dietitian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dietitians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Anna Kowalska",
                            Specialization = "Dietetyka kliniczna"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Michał Nowak",
                            Specialization = "Dietetyka sportowa"
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stopniowa redukcja masy ciała przy zachowaniu zdrowych nawyków.",
                            GoalType = "Redukcja",
                            TargetWeightKg = 76.0m,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Regularne posiłki i ograniczenie cukru.",
                            GoalType = "Zdrowsze odżywianie",
                            TargetWeightKg = 66.0m,
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 370,
                            Carbs = 60m,
                            Fat = 7m,
                            Name = "Płatki owsiane",
                            Protein = 13m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 89,
                            Carbs = 23m,
                            Fat = 0m,
                            Name = "Banan",
                            Protein = 1m,
                            Sugar = 12m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 165,
                            Carbs = 0m,
                            Fat = 4m,
                            Name = "Kurczak",
                            Protein = 31m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 15,
                            Carbs = 3m,
                            Fat = 0m,
                            Name = "Sałata",
                            Protein = 1m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 98,
                            Carbs = 3m,
                            Fat = 5m,
                            Name = "Twaróg",
                            Protein = 11m,
                            Sugar = 3m
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 420,
                            Carbs = 62m,
                            CategoryId = 1,
                            Description = "Płatki owsiane z bananem i jogurtem",
                            Fat = 10m,
                            Name = "Owsianka z owocami",
                            Protein = 18m,
                            Sugar = 18m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 560,
                            Carbs = 28m,
                            CategoryId = 2,
                            Description = "Lekki posiłek z warzywami i grillowanym kurczakiem",
                            Fat = 25m,
                            Name = "Sałatka z kurczakiem",
                            Protein = 42m,
                            Sugar = 8m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 390,
                            Carbs = 48m,
                            CategoryId = 3,
                            Description = "Pełnoziarniste pieczywo z twarożkiem i warzywami",
                            Fat = 12m,
                            Name = "Kanapki z twarożkiem",
                            Protein = 24m,
                            Sugar = 6m
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("MealId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MealIngredients");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            MealId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            MealId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            MealId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            MealId = 3,
                            IngredientId = 5
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DietitianId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietitianId = 1,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DietitianId = 1,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DietitianId = 2,
                            IsAvailable = true,
                            StartTime = new DateTime(2026, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightCm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            FullName = "Jan Testowy",
                            Gender = "Mężczyzna",
                            HeightCm = 178
                        },
                        new
                        {
                            Id = 2,
                            Age = 72,
                            FullName = "Babcia Maria",
                            Gender = "Kobieta",
                            HeightCm = 164
                        });
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Appointment", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Dietitian", "Dietitian")
                        .WithMany("Appointments")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietPlannerAPI.Models.UserProfile", "UserProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.BodyMeasurement", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.UserProfile", "UserProfile")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DayPlan", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.DietPlan", "DietPlan")
                        .WithMany("DayPlans")
                        .HasForeignKey("DietPlanId");

                    b.HasOne("DietPlannerAPI.Models.Meal", "Meal")
                        .WithMany("DayPlans")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietPlannerAPI.Models.UserProfile", "UserProfile")
                        .WithMany("DayPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlan");

                    b.Navigation("Meal");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Goal", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.UserProfile", "UserProfile")
                        .WithMany("Goals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Category", "Category")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.MealIngredient", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietPlannerAPI.Models.Meal", "Meal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.TimeSlot", b =>
                {
                    b.HasOne("DietPlannerAPI.Models.Dietitian", "Dietitian")
                        .WithMany("TimeSlots")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Category", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.DietPlan", b =>
                {
                    b.Navigation("DayPlans");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Dietitian", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.Meal", b =>
                {
                    b.Navigation("DayPlans");

                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("DietPlannerAPI.Models.UserProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BodyMeasurements");

                    b.Navigation("DayPlans");

                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
